# /root/apps/ai/app/main.py
from fastapi import FastAPI, UploadFile, File, HTTPException, status
from pydantic import BaseModel, Field
from app.services.gemini_moderation import is_image_unsafe  
from app.services.gemini_summarizer import GeminiTextSummarizer, SummaryStyle
from app.services.whisper_service import (
    TranscribeRequest,
    TranscribeResponse,
    DownloadError,
    UnsupportedMediaError,
)
from app.services import whisper_service


app = FastAPI(
    title="AI Service",
    description="AI features: Transcription, Moderation, Summarization",
    version="1.1.0"
)

@app.get("/health")
async def health_check():
    """Health check endpoint for Docker"""
    return {"status": "healthy", "service": "ai"}

@app.get("/")
async def root():
    return {"message": "AI Service is running. See /docs for API documentation."}

@app.post("/moderation/image")
async def moderate_image(file: UploadFile = File(...)):
    if file.content_type not in ("image/jpeg", "image/png", "image/webp", "image/gif"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only image files are allowed.",
        )

    image_bytes = await file.read()
    unsafe = is_image_unsafe(image_bytes=image_bytes, mime_type=file.content_type)
    return {"unsafe": unsafe}


class TranscribeAndSummarizeRequest(TranscribeRequest):
    """
    Add a style field to the existing TranscribeRequest 
    so that the request model can receive “how to summarize” in a single request.
    """
    style: SummaryStyle = Field(
        default=SummaryStyle.BRIEF,
        description="Summary style: brief, detailed, or bullet_points",
    )


class TranscribeAndSummarizeResponse(BaseModel):
    """
    The final response to be returned to the client:
	•	transcript: the full text obtained from Whisper
	•	summary: the summary generated by Gemini
    """
    transcript: str = Field(..., description="Full transcript text from Whisper")
    summary: str = Field(..., description="Generated summary from Gemini")
    style: SummaryStyle = Field(..., description="Summary style used")

@app.post(
    "/transcribe-and-summarize",
    response_model=TranscribeAndSummarizeResponse,
    summary="Transcribe audio/video and summarize with Gemini",
    description=(
        "1) Uses Whisper service to transcribe the input (e.g., from a presigned URL) "
        "and 2) summarizes the resulting text with Google Gemini. "
        "You can choose summary style: brief, detailed, or bullet_points."
    ),
)
def transcribe_and_summarize(payload: TranscribeAndSummarizeRequest) -> TranscribeAndSummarizeResponse:
    """
    High-level pipeline:
    1. whisper_service.transcribe(...) → {'text': ...}
    2. GeminiTextSummarizer.summarize(text=..., style=...)
    3. transcript + summary 함께 반환
    """
    # 1) Transcribe phase
    try:
        # assuming whisper_service.transcribe is sync
        transcribe_result: TranscribeResponse = whisper_service.transcribe(payload)
    except DownloadError as de:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to download media for transcription: {de}",
        )
    except UnsupportedMediaError as ue:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported media for transcription: {ue}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Unexpected error during transcription: {e}",
        )

    # cc_result = transcribe() would return {'text': "..."} 
    # assuming there would be text field in TranscribeResponse
    transcript_text = getattr(transcribe_result, "text", None) or getattr(
        transcribe_result, "transcript", None
    )

    if not transcript_text or not transcript_text.strip():
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Transcription returned empty text; cannot summarize.",
        )

    # 2) Summarize phase
    try:
        summarizer = GeminiTextSummarizer()
        summary_text = summarizer.summarize(
            text=transcript_text,
            style=payload.style,
        )
    except ValueError as ve:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(ve),
        )
    except RuntimeError as re:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=str(re),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Unexpected error during summarization: {e}",
        )

    # 3) return transcript + summary
    return TranscribeAndSummarizeResponse(
        transcript=transcript_text,
        summary=summary_text,
        style=payload.style,
    )
