# apps/ai/app/api/routes/summarize.py

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from apps.ai.app.services.gemini_summarizer import (
    GeminiTextSummarizer,
    SummaryStyle,
)

router = APIRouter(prefix="/summarize", tags=["summarization"])


class SummarizeRequest(BaseModel):
    text: str = Field(
        ...,
        description=(
            "Raw text to summarize. "
            "You can load transcript text from MinIO and pass it here."
        ),
    )
    style: SummaryStyle = Field(
        default=SummaryStyle.BRIEF,
        description="Summary style: brief, detailed, or bullet_points",
    )


class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="Generated summary from Gemini")


@router.post(
    "",
    response_model=SummarizeResponse,
    summary="Summarize text with Google Gemini",
    description=(
        "Accepts plain text (e.g., transcript loaded from MinIO) and returns a "
        "summary generated by Google Gemini. Supports multiple styles: "
        "`brief`, `detailed`, `bullet_points`."
    ),
)
def summarize_text(payload: SummarizeRequest) -> SummarizeResponse:
    """
    Endpoint for text summarization.
    deliver text to this endpoint after reading transcript text from MinIO
    """
    try:
        summarizer = GeminiTextSummarizer()
        summary = summarizer.summarize(
            text=payload.text,
            style=payload.style,
        )
        return SummarizeResponse(summary=summary)
    except ValueError as ve:
        # input issue (text is blank)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(ve),
        )
    except RuntimeError as re:
        # fail to call Gemini (weird response, etc.)
        
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=str(re),
        )
    except Exception as e:
        # unexpected error
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Unexpected error during summarization: {e}",
        )
